Fix build for clang compiler
[  278s] ../../../dali-extension/video-player/base/video-player-base.h:216:8: error: 'Forward' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
[  278s]   216 |   void Forward(int millisecond);
[  278s]       |        ^

[  148s] ../../../dali-extension/video-player/es-video-player/es-video-player.cpp:33:11: error: unused variable 'MAX_QUEUE_SIZE' [-Werror,-Wunused-const-variable]
[  148s]    33 | const int MAX_QUEUE_SIZE = 3;
[  148s]       |           ^~~~~~~~~~~~~~

Fixed Clang -Werror failures by marking Forward/Backward as override and removing unused video-player constants that triggered -Wunused-const-variable.

Change-Id: If65fd20fb32948f20ea20c7a944d8bb2132456e8
Signed-off-by: Kai Cheng <kai.cheng@samsung.com>